pipeline:
  identifier: Build_DevOps_Project_1687411027142
  name: Build DevOps-Project
  orgIdentifier: default
  projectIdentifier: UALPOC
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1687410971941
        repoName: praveenjirra/DevOps-Project
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                    connectorRef: account.harnessImage
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
